name: My first githubaction file
on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script."
          echo "It can contain multiple commands."
      - name: Upload one more line script
        run: echo "This is another one-line script."
      - name: Run a script with fouthe file
        run: |
          echo "This is a script with fouthe file."
          echo "It can also contain multiple commands."