name: My first githubaction file
on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"
      
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest
    
      - name : testing the installation
        run : |
           cd src
           python -m pytest addition.py
    
  Install-apache:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4 # Action to check out the repository code

        - name: Install Apache2
          run: sudo apt install apache2 -y # Install the Apache2 package

        - name: start apache2 service
          run: sudo systemctl start apache2 # Start the Apache2 service
        

    





