name: My first githubaction file
on:
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, World!"
      
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you want to use
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest
    
      - name : testing the installation
        run : |
           cd src
           python -m pytest addition.py


